CREATE TABLE combos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco_venda DECIMAL(10,2) NOT NULL DEFAULT 0,
    descricao TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    desconto_percentual DECIMAL(5,2) DEFAULT 0,
    valido_ate DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
